### ISSUE TITLE
按 SHIFT-Space 切換半/全型時，顯示在游標旁的提示不正確，都顯示為「全型」

### ISSUE THREAD

**Issue by xohawke** [jrywu/DIME#66]

**Comment by dohanin** [comment]
I found the bug in the source file SetupCompositionProcesseorEngine.cpp
Line 568
Instead of    `	if (_pTextService) _pTextService->showFullHalfShapeNotify(~isDouble);`
It should be `	if (_pTextService) _pTextService->showFullHalfShapeNotify(!isDouble);`

I recompiled the DIME.dll object and it works.  
Hope @jrywu will fix it in the next release.

**Comment by xohawke** [comment]
Hi dohanin, may I get new DIME.dll from you? Appreciated...

**Comment by jrywu** [comment]
已於 DIME v1.2.341 修正
